"""Invoice PDF generator (fpdf2) — amount is exact integer minor units."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from fpdf import FPDF

from .money import DEFAULT_CURRENCY, format_money


def generate_invoice_pdf(
    client: str,
    amount_minor: int,
    currency: str = DEFAULT_CURRENCY,
    description: str = "Professional services",
    out: Path = Path("invoice.pdf"),
) -> Path:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "INVOICE - localfiscal", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Date: {date.today().isoformat()}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Client: {client}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(
        0, 8, f"{description}: {format_money(amount_minor, currency)}",
        new_x="LMARGIN", new_y="NEXT",
    )
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(
        0, 6,
        "Thank you for your business.\n\n"
        "Payment instructions: local wire or your preferred method.\n\n"
        "- generated by localfiscal (private, no SaaS)",
    )
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(out))
    return out
