"""Invoice PDF generator (ambitious clean output)."""

from pathlib import Path
from datetime import date
from fpdf import FPDF

def generate_invoice_pdf(client: str, amount: float, description: str, out: Path) -> Path:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "INVOICE - localfiscal", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Date: {date.today().isoformat()}", ln=True)
    pdf.cell(0, 8, f"Client: {client}", ln=True)
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, f"{description}: ${amount:.2f}", ln=True)
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, "Thank you for your business.\n\nPayment instructions: local wire or your preferred method.\n\n- generated by localfiscal (private, no SaaS)")
    out.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(out))
    return out
